# This configuration deploys both the main-app and music-library to the same domain.

[build]
  # Base directory for the monorepo
  base = "."
  # The command to build both apps
  command = "npm run build:all"
  # The final output directory that Netlify will deploy
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
